#spring:
#  application:
#    name: ORDER-SERVICE
#server:
#  port: 8081
#eureka:
#  instance:
##    prefer-ip-address: true
##    hostname: localhost
#  client:
#    fetch-registry: true
#    register-with-eureka: true
##    enabled: true
##    service-url:
##      defaultZone: http://localhost:8761/eureka/
#
